/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.pig.piggybank.test.storage.avro.stringType;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class stringTypeTestSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"stringTypeTestSchema\",\"namespace\":\"org.apache.pig.piggybank.test.storage.avro.stringType\",\"fields\":[{\"name\":\"field\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String field;

  /**
   * Default constructor.
   */
  public stringTypeTestSchema() {}

  /**
   * All-args constructor.
   */
  public stringTypeTestSchema(java.lang.String field) {
    this.field = field;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return field;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: field = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'field' field.
   */
  public java.lang.String getField() {
    return field;
  }

  /**
   * Sets the value of the 'field' field.
   * @param value the value to set.
   */
  public void setField(java.lang.String value) {
    this.field = value;
  }

  /** Creates a new stringTypeTestSchema RecordBuilder */
  public static org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder newBuilder() {
    return new org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder();
  }
  
  /** Creates a new stringTypeTestSchema RecordBuilder by copying an existing Builder */
  public static org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder newBuilder(org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder other) {
    return new org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder(other);
  }
  
  /** Creates a new stringTypeTestSchema RecordBuilder by copying an existing stringTypeTestSchema instance */
  public static org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder newBuilder(org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema other) {
    return new org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder(other);
  }
  
  /**
   * RecordBuilder for stringTypeTestSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<stringTypeTestSchema>
    implements org.apache.avro.data.RecordBuilder<stringTypeTestSchema> {

    private java.lang.String field;

    /** Creates a new Builder */
    private Builder() {
      super(org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing stringTypeTestSchema instance */
    private Builder(org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema other) {
            super(org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.SCHEMA$);
      if (isValidValue(fields()[0], other.field)) {
        this.field = data().deepCopy(fields()[0].schema(), other.field);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'field' field */
    public java.lang.String getField() {
      return field;
    }
    
    /** Sets the value of the 'field' field */
    public org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder setField(java.lang.String value) {
      validate(fields()[0], value);
      this.field = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'field' field has been set */
    public boolean hasField() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'field' field */
    public org.apache.pig.piggybank.test.storage.avro.stringType.stringTypeTestSchema.Builder clearField() {
      field = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public stringTypeTestSchema build() {
      try {
        stringTypeTestSchema record = new stringTypeTestSchema();
        record.field = fieldSetFlags()[0] ? this.field : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
